export const spells = [
  {
    id: 1,
    name: "Ant",
    image: require("../images/learning/ant.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 2,
    name: "Ball",
    image: require("../images/learning/ball.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 3,
    name: "Car",
    image: require("../images/learning/car.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 4,
    name: "Drum",
    image: require("../images/learning/drum.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 5,
    name: "egg",
    image: require("../images/learning/egg.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 6,
    name: "fish",
    image: require("../images/learning/fish.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 7,
    name: "grapes",
    image: require("../images/learning/grapes.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 8,
    name: "Hat",
    image: require("../images/learning/hat.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 9,
    name: "Ice",
    image: require("../images/learning/ice.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 10,
    name: "Jar",
    image: require("../images/learning/jar.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 11,
    name: "Kite",
    image: require("../images/learning/kite.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 12,
    name: "Lamp",
    image: require("../images/learning/lamp.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 13,
    name: "Moon",
    image: require("../images/learning/moon.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 14,
    name: "Nest",
    image: require("../images/learning/nest.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 15,
    name: "Orange",
    image: require("../images/learning/orange.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 16,
    name: "Pea",
    image: require("../images/learning/pea.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 17,
    name: "Quilt",
    image: require("../images/learning/quilt.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 18,
    name: "Rose",
    image: require("../images/learning/rose.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 19,
    name: "Sun",
    image: require("../images/learning/sun.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 20,
    name: "Tap",
    image: require("../images/learning/tap.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 21,
    name: "Urn",
    image: require("../images/learning/urn.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 22,
    name: "Vase",
    image: require("../images/learning/vase.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 23,
    name: "Web",
    image: require("../images/learning/web.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 24,
    name: "X-Rays",
    image: require("../images/learning/x-rays.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 25,
    name: "Yolk",
    image: require("../images/learning/yolk.png"),
    iconImage: require("../images/learning/voice.png"),
  },
  {
    id: 26,
    name: "Zip",
    image: require("../images/learning/zip.png"),
    iconImage: require("../images/learning/voice.png"),
  },
];
